#!/bin/bash

hashprogram="xxhsum"
hashextension="xx"

if [ ! -n "$1" ]; then
	echo "Must give file location (on remote machine) as argument"
	echo "This file location follows the same format as in scp."
	exit 0
fi

rmchecksum="true"
scpargs=""
for arg in "$@"; do
	if [ "$arg" == "--no-rm-checksum" ]; then
		rmchecksum="false"
	else
		scpargs="$scpargs $arg"
	fi
done

echo "scpargs: $scpargs"

checksumurl=$scpargs
checksumfile=$(echo $checksumurl | tr '/' ' ' | rev | awk '{print $1}' | rev)
baseurl=$(echo $checksumurl | rev | colrm 1 $(expr length $checksumfile) | rev)

while : ; do

	badfiles=0

	# download checksum from server
	if [ ! -f $checksumfile ]; then
		scp $checksumurl ./
		if [ ! -f $checksumfile ]; then
			echo "ERROR: could not download checksum file"
			exit 1
		fi
	fi
	rm -f $checksumfile-verify

	# download files and calculate checksums
	current=0
	numfiles=$(wc -l $checksumfile | awk '{print $1}')
	for file in $(cat $checksumfile | awk '{print $2}'); do
		((current=current+1))
		if [ ! -f $file ]; then
			clear
			if [ -n "$(which toilet)" ]; then
				toilet "$current / $numfiles"
			fi
			echo "Downloading file $file of $numfiles ... "
			scp $baseurl$file ./
		fi
		if [ ! -f $file.$hashextension ]; then
			clear
			if [ -n "$(which toilet)" ]; then
				toilet "$current / $numfiles"
			fi
			echo "Calculating $hashextension checksum for $file ... "
			$hashprogram $file >> $file.$hashextension
		fi
		cat $file.$hashextension >> $checksumfile-verify
	done

	# verify checksums
	clear
	if [ -n "$(diff $checksumfile $checksumfile-verify)" ]; then
		diff $checksumfile $checksumfile-verify
		echo "file integrity compromised!"
		for line in $(diff $checksumfile $checksumfile-verify | awk '{print $3}'); do
			if [ -n "$(echo $line | colrm 1 1)" ]; then
				rm $line $line.$hashextension
				((badfiles=badfiles+1))
			fi
		done
		echo "there are $badfiles bad files"
		echo "attemping to correct ... "
	else
		echo "file integrity verified"
		for file in $(cat $checksumfile | awk '{print $2}'); do
			rm $file.$hashextension
		done
		if [ "$rmchecksum" == "true" ]; then
			rm $checksumfile
		fi
		rm $checksumfile-verify
	fi

	[[ "$badfiles" -gt "0" ]] || break
done
