#!/bin/bash

username=""
password=""
checksumurl=""

rmchecksum="true"

for var in "$@"; do
	if [ "$var" == "--no-rm-checksum" ]; then
		rmchecksum="false"
	fi
	if [ "$(echo $var | tr '=' ' ' | awk '{print $1}')" == "--user" ]; then
		username="$(echo $var | tr '=' ' ' | awk '{print $2}')"
	else
		if [ "$(echo $var | tr '=' ' ' | awk '{print $1}')" == "--password" ]; then
        	        password="$(echo $var | tr '=' ' ' | awk '{print $2}')"
		else
			checksumurl="$var"
		fi
	fi
done

if [ ! -n "$checksumurl" ]; then
	echo "Must include url as argument"
	echo "Usage: download <url>"
	echo "       download <url> <user> <password>"
	exit 1
fi

checksumfile=$(echo $checksumurl | tr '/' ' ' | rev | awk '{print $1}' | rev)
baseurl=$(echo $checksumurl | rev | colrm 1 $(expr length $checksumfile) | rev)

while : ; do

	badfiles=0

	# download checksum from server
	if [ ! -f $checksumfile ]; then
		if [ -n "$username" ] || [ -n "$password" ]; then
			wget --user=$username --password=$password $checksumurl
		else
			wget $checksumurl
		fi
		if [ ! -f $checksumfile ]; then
			echo "ERROR: could not download checksum file"
			exit 1
		fi
	fi
	rm -f $checksumfile-verify

	# download files and calculate checksums
	current=0
	numfiles=$(wc -l $checksumfile | awk '{print $1}')
	for file in $(cat $checksumfile | awk '{print $2}'); do
		((current=current+1))
		if [ ! -f $file ]; then
			clear
			if [ -n "$(which toilet)" ]; then
				toilet "$current / $numfiles"
			fi
			echo "Downloading file $file of $numfiles ... "
			if [ -n "$username" ] || [ -n "$password" ]; then
				wget --user=$username --password=$password $baseurl$file
			else
				wget $baseurl$file
			fi
		fi
		if [ ! -f $file.md5 ]; then
			clear
			if [ -n "$(which toilet)" ]; then
				toilet "$current / $numfiles"
			fi
			echo "Calculating md5 checksum for $file ... "
			md5sum $file >> $file.md5
		fi
		cat $file.md5 >> $checksumfile-verify
	done

	# verify checksums
	clear
	if [ -n "$(diff $checksumfile $checksumfile-verify)" ]; then
		diff $checksumfile $checksumfile-verify
		echo "file integrity compromised!"
		for line in $(diff $checksumfile $checksumfile-verify | awk '{print $3}'); do
			if [ -n "$(echo $line | colrm 1 1)" ]; then
				rm $line $line.md5
				((badfiles=badfiles+1))
			fi
		done
		echo "there are $badfiles bad files"
		echo "attemping to correct ... "
	else
		echo "file integrity verified"
		for file in $(cat $checksumfile | awk '{print $2}'); do
			rm $file.md5
		done
		if [ "$rmchecksum" == "true" ]; then
			rm $checksumfile
		fi
		rm $checksumfile-verify
	fi

	[[ "$badfiles" -gt "0" ]] || break
done

