#!/bin/bash

if [ -z "$1" ]; then
	echo "ERROR: must specify filename of md5 checksum file"
	exit 0
fi

if [ -f "$1" ]; then
	echo "ERROR: file $1 already exists"
	exit 0
	read -p "WARNING: file exists. Replace? (y/n) " -n 1 -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		echo "overwriting"
		rm -f $1
	else
		echo "not overwriting file $1"
		exit 0
	fi
fi

count=0
total="$(ls | wc -l | awk '{print $1}')"
for file in $(ls); do
	((count=count+1))
	#echo " $count / $total   $file"
	printf "%3d / %d   %s\n" $count $total $file
	md5sum $file >> $1
done

cat $1
echo "done!"
