#!/bin/bash

control_c()
{
	echo -en "\n*** Exiting without further progress ***\n"
	exit $?
}

# trap keyboard interrupt (control-c)
trap control_c SIGINT

for dir in $(ls); do
	if [ -d $dir ]; then
		cd $dir
		7za a -mx=0 -v256m $dir.7z *
		find ! -name "*.7z.*" -delete
		prepare $dir.md5
		printf "\n"
		cd ..
	fi
done
